steps:
# npm install in the logger directory
#- name: 'gcr.io/cloud-builders/npm'
#  args: ['install', '--prefix', './plugins/logger']

# set the edgemicro version with the metadata field
- name: gcr.io/cloud-builders/gcloud
  args: ['compute', 'instances', 'add-metadata', 'edge-microgateway-1', '--metadata', 'EM_VERSION=$TAG_NAME', '--project', '$PROJECT_ID', '--zone', 'us-central1-c']
  timeout: 60s

# update edgemicrogateway with the following shell script
#- name: gcr.io/cloud-builders/gcloud
#  args: ['compute', 'scp', '--project', '$PROJECT_ID', '--zone', 'us-central1-c', './update-edgemicro.sh', 'edge-microgateway-1:~']

#- name: gcr.io/cloud-builders/gcloud
#  args: ['compute', 'scp', '--project', '$PROJECT_ID', '--zone', 'us-central1-c', './update-edgemicro.sh', 'edge-microgateway-2:~']
#  volumes:
#  - name: 'vol1'
#    path: '/mypath'

- name: gcr.io/cloud-builders/gcloud
  args: ['compute', 'ssh', 'edge-microgateway-1', '--project', '$PROJECT_ID', '--zone', 'us-central1-c', '--command', '/tmp/restart-edgemicro.sh']
  timeout: 60s

- name: gcr.io/cloud-builders/gcloud
  args: ['compute', 'ssh', 'edge-microgateway-2', '--project', '$PROJECT_ID', '--zone', 'us-central1-c', '--command', '/tmp/restart-edgemicro.sh']
